#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Script pour créer les pages WordPress pour le système Video Library Protect
"""

import os
from datetime import datetime

def create_page_file(filename, title, content, description=""):
    """Créer un fichier de page WordPress"""
    
    # Template de base pour une page WordPress
    page_template = f'''<?php
/**
 * Page: {title}
 * Description: {description}
 * 
 * Generated by Video Library Protect page creator
 * Date: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
 */

// Prevent direct access
if (!defined('ABSPATH')) {{
    exit;
}}

/**
 * {title}
 * 
 * Cette page fait partie du système Video Library Protect
 * et utilise les shortcodes et fonctionnalités du plugin.
 */

// Page Header
get_header(); ?>

<div class="vlp-page-wrapper">
    <div class="container">
        <main class="vlp-main-content">
            
            <header class="vlp-page-header">
                <h1 class="vlp-page-title">{title}</h1>
                <?php if (!empty("{description}")): ?>
                <p class="vlp-page-description">{description}</p>
                <?php endif; ?>
            </header>

            <div class="vlp-page-content">
{content}
            </div>

        </main>
    </div>
</div>

<style>
.vlp-page-wrapper {{
    padding: 40px 0;
    background: #f8f9fa;
    min-height: 70vh;
}}

.vlp-page-header {{
    text-align: center;
    margin-bottom: 40px;
    padding: 30px 0;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}}

.vlp-page-title {{
    color: #2c3e50;
    font-size: 2.5em;
    margin-bottom: 15px;
    font-weight: 600;
}}

.vlp-page-description {{
    color: #7f8c8d;
    font-size: 1.2em;
    max-width: 600px;
    margin: 0 auto;
    line-height: 1.6;
}}

.vlp-page-content {{
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}}

.vlp-info-box {{
    background: #e8f4fd;
    border-left: 4px solid #3498db;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}}

.vlp-warning-box {{
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}}

.vlp-success-box {{
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}}

.vlp-steps-list {{
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin: 30px 0;
}}

.vlp-steps-list ol {{
    counter-reset: step-counter;
    list-style: none;
    padding: 0;
}}

.vlp-steps-list ol li {{
    counter-increment: step-counter;
    margin: 20px 0;
    padding: 20px;
    background: white;
    border-radius: 6px;
    position: relative;
    padding-left: 60px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}}

.vlp-steps-list ol li::before {{
    content: counter(step-counter);
    position: absolute;
    left: 20px;
    top: 20px;
    background: #3498db;
    color: white;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    font-size: 14px;
}}

.vlp-code-example {{
    background: #2c3e50;
    color: #ecf0f1;
    padding: 20px;
    border-radius: 6px;
    font-family: 'Courier New', monospace;
    margin: 20px 0;
    overflow-x: auto;
}}

.vlp-shortcode-demo {{
    background: #f39c12;
    color: white;
    padding: 15px;
    border-radius: 4px;
    font-family: monospace;
    text-align: center;
    margin: 15px 0;
    font-weight: bold;
}}

@media (max-width: 768px) {{
    .vlp-page-title {{
        font-size: 2em;
    }}
    
    .vlp-page-content {{
        padding: 20px;
    }}
    
    .vlp-steps-list ol li {{
        padding-left: 20px;
    }}
    
    .vlp-steps-list ol li::before {{
        position: relative;
        left: 0;
        top: 0;
        margin-right: 15px;
        margin-bottom: 10px;
    }}
}}
</style>

<?php get_footer(); ?>
'''

    with open(filename, 'w', encoding='utf-8') as f:
        f.write(page_template)
    
    print(f"✅ Page créée: {filename}")

def main():
    """Fonction principale pour créer toutes les pages"""
    
    # Créer le dossier pages s'il n'existe pas
    pages_dir = "pages"
    if not os.path.exists(pages_dir):
        os.makedirs(pages_dir)
    
    print("🎬 Création des pages pour Video Library Protect")
    print("=" * 50)
    
    # 1. Page Bibliothèque Vidéo (automatiquement créée par le plugin)
    video_library_content = '''
                <!-- Shortcode principal pour afficher la bibliothèque vidéo -->
                <div class="vlp-info-box">
                    <h3>🎥 Votre Bibliothèque Vidéo</h3>
                    <p>Cette page affiche toutes vos vidéos disponibles. Les vidéos peuvent être gratuites ou protégées par des codes cadeaux.</p>
                </div>

                <!-- Shortcode de la bibliothèque vidéo -->
                [vlp_video_library]

                <div class="vlp-info-box">
                    <h4>💡 Fonctionnalités disponibles :</h4>
                    <ul>
                        <li>🔍 <strong>Recherche</strong> : Trouvez rapidement une vidéo</li>
                        <li>📁 <strong>Filtres par catégorie</strong> : Naviguez par thème</li>
                        <li>🔒 <strong>Protection par codes</strong> : Accès sécurisé aux contenus premium</li>
                        <li>👁️ <strong>Aperçus gratuits</strong> : Découvrez le contenu avant l'achat</li>
                        <li>📱 <strong>Design responsive</strong> : Fonctionne sur tous les appareils</li>
                    </ul>
                </div>

                <div class="vlp-success-box">
                    <p><strong>🎯 Astuce :</strong> Si vous avez des codes cadeaux, saisissez-les directement sur les vidéos protégées pour débloquer l'accès complet !</p>
                </div>
    '''

    create_page_file(
        f"{pages_dir}/page-video-library.php",
        "Bibliothèque Vidéo",
        video_library_content,
        "Page principale pour découvrir et regarder toutes nos vidéos"
    )

    # 2. Page Catégories de Vidéos
    categories_content = '''
                <!-- Shortcode pour afficher les catégories -->
                <div class="vlp-info-box">
                    <h3>📁 Explorez nos Catégories</h3>
                    <p>Découvrez nos vidéos organisées par thèmes et sujets. Chaque catégorie peut avoir son propre niveau de protection.</p>
                </div>

                <!-- Shortcode des catégories vidéo -->
                [vlp_video_categories layout="grid" columns="3" show_count="true" show_protected="true"]

                <div class="vlp-steps-list">
                    <h4>🚀 Comment naviguer dans les catégories :</h4>
                    <ol>
                        <li>
                            <strong>Parcourez les catégories</strong><br>
                            Chaque catégorie affiche le nombre de vidéos et son statut de protection
                        </li>
                        <li>
                            <strong>Identifiez les protections</strong><br>
                            L'icône 🔒 indique qu'un code cadeau est requis pour accéder au contenu
                        </li>
                        <li>
                            <strong>Cliquez pour explorer</strong><br>
                            Accédez directement aux vidéos de la catégorie qui vous intéresse
                        </li>
                        <li>
                            <strong>Utilisez vos codes</strong><br>
                            Saisissez votre code cadeau pour débloquer une catégorie entière
                        </li>
                    </ol>
                </div>

                <div class="vlp-warning-box">
                    <h4>🔑 Codes Cadeaux Requis</h4>
                    <p>Certaines catégories nécessitent un code cadeau valide. Une fois un code saisi, vous aurez accès à toutes les vidéos de cette catégorie !</p>
                </div>
    '''

    create_page_file(
        f"{pages_dir}/page-categories-videos.php",
        "Catégories de Vidéos",
        categories_content,
        "Naviguez dans nos vidéos par catégories thématiques"
    )

    # 3. Page de Contenu Protégé (exemple)
    protected_content = '''
                <div class="vlp-info-box">
                    <h3>🔒 Contenu Exclusif</h3>
                    <p>Cette page démontre comment protéger du contenu spécifique avec des codes cadeaux personnalisés.</p>
                </div>

                <!-- Contenu protégé par codes spécifiques -->
                [vlp_protected_content codes="VIP-ACCESS,PREMIUM-2024" message="Ce contenu exclusif nécessite un code VIP ou Premium." unlock_message="🎉 Bienvenue dans notre espace VIP !"]

                <h3>🌟 Contenu Exclusif VIP</h3>
                <p>Félicitations ! Vous avez débloqué notre contenu exclusif.</p>

                <div class="vlp-success-box">
                    <h4>🎁 Avantages VIP inclus :</h4>
                    <ul>
                        <li>✨ Accès anticipé aux nouvelles vidéos</li>
                        <li>🎥 Contenu bonus et coulisses</li>
                        <li>💬 Communauté privée VIP</li>
                        <li>📧 Newsletter exclusive avec conseils privés</li>
                        <li>🎯 Formations avancées réservées aux membres</li>
                    </ul>
                </div>

                <div class="vlp-code-example">
Codes acceptés pour cette page :
- VIP-ACCESS (accès illimité)
- PREMIUM-2024 (accès premium annuel)
                </div>

                <!-- Autre section protégée avec code différent -->
                [vlp_protected_content codes="MASTERCLASS-2024" message="Cette masterclass exclusive nécessite le code MASTERCLASS-2024"]

                <h3>🎓 Masterclass Exclusive</h3>
                <p>Cette formation approfondie vous donnera les clés pour maîtriser [votre sujet].</p>

                <video controls width="100%">
                    <source src="/path/to/exclusive-masterclass.mp4" type="video/mp4">
                    Votre navigateur ne supporte pas la lecture vidéo.
                </video>

                [/vlp_protected_content]

                [/vlp_protected_content]

                <div class="vlp-info-box">
                    <h4>🛡️ Comment fonctionne la protection :</h4>
                    <p>Le shortcode <code>[vlp_protected_content]</code> permet de protéger n'importe quel contenu avec des codes spécifiques. 
                    Seuls les utilisateurs ayant saisi un code valide peuvent voir le contenu à l'intérieur.</p>
                </div>
    '''

    create_page_file(
        f"{pages_dir}/page-contenu-protege-exemple.php",
        "Contenu Protégé - Exemple",
        protected_content,
        "Exemple de page avec du contenu protégé par codes cadeaux"
    )

    # 4. Page Aide/Support Vidéo
    help_content = '''
                <div class="vlp-info-box">
                    <h3>❓ Centre d'Aide - Video Library Protect</h3>
                    <p>Trouvez rapidement les réponses à vos questions sur l'utilisation de notre bibliothèque vidéo et des codes cadeaux.</p>
                </div>

                <div class="vlp-steps-list">
                    <h4>🚀 Guide de démarrage rapide :</h4>
                    <ol>
                        <li>
                            <strong>Découvrez la bibliothèque</strong><br>
                            Rendez-vous sur la <a href="/video-library/">page de la bibliothèque vidéo</a> pour voir toutes les vidéos disponibles
                        </li>
                        <li>
                            <strong>Explorez les catégories</strong><br>
                            Naviguez par thème sur la <a href="/categories-videos/">page des catégories</a>
                        </li>
                        <li>
                            <strong>Regardez les aperçus gratuits</strong><br>
                            Toutes les vidéos ont un aperçu gratuit pour vous aider à choisir
                        </li>
                        <li>
                            <strong>Utilisez vos codes cadeaux</strong><br>
                            Saisissez votre code pour débloquer la vidéo complète ou une catégorie entière
                        </li>
                    </ol>
                </div>

                <h3>🔑 Utilisation des Codes Cadeaux</h3>

                <div class="vlp-warning-box">
                    <h4>Format des codes :</h4>
                    <ul>
                        <li>Entre 3 et 50 caractères</li>
                        <li>Lettres, chiffres et tirets autorisés</li>
                        <li>Pas de distinction majuscules/minuscules</li>
                        <li>Exemples : <code>NOEL2024</code>, <code>promo-hiver</code>, <code>VIP-ACCESS</code></li>
                    </ul>
                </div>

                <div class="vlp-steps-list">
                    <h4>📝 Comment saisir un code cadeau :</h4>
                    <ol>
                        <li>
                            <strong>Sur une vidéo protégée</strong><br>
                            Cliquez sur la vidéo, puis saisissez votre code dans le formulaire qui apparaît
                        </li>
                        <li>
                            <strong>Pour une catégorie entière</strong><br>
                            Le code vous donnera accès à toutes les vidéos de cette catégorie
                        </li>
                        <li>
                            <strong>Sur du contenu spécifique</strong><br>
                            Certaines pages ont du contenu protégé par des codes particuliers
                        </li>
                        <li>
                            <strong>Accès site entier</strong><br>
                            Certains codes premium donnent accès à l'ensemble du site
                        </li>
                    </ol>
                </div>

                <h3>🎥 Types de Protection</h3>

                <div class="vlp-info-box">
                    <h4>🆓 Vidéos gratuites</h4>
                    <p>Accès immédiat et complet à la vidéo, sans code requis.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>🔒 Vidéos protégées individuellement</h4>
                    <p>Chaque vidéo a ses propres codes d'accès. L'aperçu est gratuit, la vidéo complète nécessite un code.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>📁 Catégories protégées</h4>
                    <p>Un seul code donne accès à toutes les vidéos de la catégorie.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>🌐 Protection site entier</h4>
                    <p>Certains codes premium donnent accès à l'intégralité du contenu du site.</p>
                </div>

                <h3>🛠️ Résolution de problèmes</h3>

                <div class="vlp-steps-list">
                    <h4>❌ Problèmes courants et solutions :</h4>
                    <ol>
                        <li>
                            <strong>"Code invalide"</strong><br>
                            ✅ Vérifiez l'orthographe et les espaces<br>
                            ✅ Assurez-vous que le code n'est pas expiré<br>
                            ✅ Contactez-nous si le problème persiste
                        </li>
                        <li>
                            <strong>"La vidéo ne se charge pas"</strong><br>
                            ✅ Vérifiez votre connexion internet<br>
                            ✅ Essayez de rafraîchir la page<br>
                            ✅ Désactivez temporairement les bloqueurs de publicité
                        </li>
                        <li>
                            <strong>"J'ai perdu mon code"</strong><br>
                            ✅ Vérifiez vos emails de confirmation<br>
                            ✅ Consultez votre compte utilisateur<br>
                            ✅ Contactez notre support client
                        </li>
                        <li>
                            <strong>"Le code ne fonctionne pas sur cette vidéo"</strong><br>
                            ✅ Vérifiez que le code correspond bien à cette vidéo<br>
                            ✅ Certains codes sont spécifiques à des catégories<br>
                            ✅ Les codes site-wide fonctionnent partout
                        </li>
                    </ol>
                </div>

                <h3>🎯 Shortcodes Disponibles</h3>

                <div class="vlp-code-example">
                    <h4>Pour les développeurs et administrateurs :</h4>

                    <!-- Bibliothèque complète -->
                    [vlp_video_library]
                    
                    <!-- Bibliothèque avec options -->
                    [vlp_video_library category="formation" limit="8" columns="4" layout="grid"]
                    
                    <!-- Catégories uniquement -->
                    [vlp_video_categories layout="grid" show_count="true"]
                    
                    <!-- Vidéo spécifique -->
                    [vlp_single_video id="123" autoplay="false" show_info="true"]
                    [vlp_single_video slug="ma-video" width="100%" show_related="true"]
                    
                    <!-- Contenu protégé -->
                    [vlp_protected_content codes="CODE1,CODE2"]Contenu secret[/vlp_protected_content]
                </div>

                <h3>📞 Besoin d'aide supplémentaire ?</h3>

                <div class="vlp-success-box">
                    <h4>💬 Contactez-nous :</h4>
                    <ul>
                        <li>📧 <strong>Email :</strong> support@votresite.com</li>
                        <li>💬 <strong>Chat en direct :</strong> Disponible 9h-18h</li>
                        <li>📱 <strong>Téléphone :</strong> +33 1 23 45 67 89</li>
                        <li>🎫 <strong>Système de tickets :</strong> <a href="/support/">Créer un ticket</a></li>
                    </ul>
                    <p><strong>⏰ Temps de réponse moyen :</strong> Moins de 2 heures en semaine</p>
                </div>

                <div class="vlp-info-box">
                    <h4>📚 Ressources utiles :</h4>
                    <ul>
                        <li><a href="/video-library/">🎥 Bibliothèque Vidéo</a></li>
                        <li><a href="/categories-videos/">📁 Catégories de Vidéos</a></li>
                        <li><a href="/mon-compte/">👤 Mon Compte</a></li>
                        <li><a href="/faq/">❓ FAQ Complète</a></li>
                    </ul>
                </div>
    '''

    create_page_file(
        f"{pages_dir}/page-aide-support-video.php",
        "Aide & Support Vidéo",
        help_content,
        "Guide complet pour utiliser la bibliothèque vidéo et les codes cadeaux"
    )

    # 5. Page d'installation/documentation pour les développeurs
    installation_content = '''
                <div class="vlp-info-box">
                    <h3>🔧 Installation et Configuration</h3>
                    <p>Guide technique pour les développeurs et administrateurs WordPress.</p>
                </div>

                <div class="vlp-steps-list">
                    <h4>⚙️ Installation du plugin :</h4>
                    <ol>
                        <li>
                            <strong>Téléchargement</strong><br>
                            Téléchargez le plugin Video Library Protect depuis votre espace client
                        </li>
                        <li>
                            <strong>Installation WordPress</strong><br>
                            Allez dans Extensions > Ajouter > Téléverser et sélectionnez le fichier ZIP
                        </li>
                        <li>
                            <strong>Activation</strong><br>
                            Activez le plugin depuis la liste des extensions
                        </li>
                        <li>
                            <strong>Configuration initiale</strong><br>
                            Le plugin créé automatiquement les tables et la page bibliothèque
                        </li>
                    </ol>
                </div>

                <h3>📁 Structure des Pages Créées</h3>

                <div class="vlp-code-example">
/video-library/                 → [vlp_video_library]
/categories-videos/             → [vlp_video_categories]
/aide-support-video/           → Documentation complète
/contenu-protege-exemple/      → Exemple de protection
</div>

                <div class="vlp-steps-list">
                    <h4>🎯 Configuration recommandée :</h4>
                    <ol>
                        <li>
                            <strong>Intégration GiftCode Protect</strong><br>
                            Installez et activez le plugin GiftCode Protect v2 pour la gestion des codes
                        </li>
                        <li>
                            <strong>Configuration Bunny Stream (optionnel)</strong><br>
                            Configurez vos clés API Bunny pour la diffusion vidéo optimisée
                        </li>
                        <li>
                            <strong>Presto Player (optionnel)</strong><br>
                            Installez Presto Player pour un lecteur vidéo avancé
                        </li>
                        <li>
                            <strong>Personnalisation CSS</strong><br>
                            Adaptez les styles dans votre thème ou via le customizer
                        </li>
                    </ol>
                </div>

                <h3>🎨 Personnalisation</h3>

                <div class="vlp-code-example">
/* CSS pour personnaliser l'apparence */
.vlp-video-library {
    /* Styles de la bibliothèque */
}

.vlp-video-card {
    /* Styles des cartes vidéo */
}

.vlp-unlock-form {
    /* Styles des formulaires de déverrouillage */
}
</div>

                <div class="vlp-warning-box">
                    <h4>⚠️ Prérequis techniques :</h4>
                    <ul>
                        <li>WordPress 5.0+</li>
                        <li>PHP 7.4+</li>
                        <li>MySQL 5.6+</li>
                        <li>Plugin GiftCode Protect v2 (recommandé)</li>
                        <li>HTTPS activé (pour la sécurité des codes)</li>
                    </ul>
                </div>

                <h3>🔌 Intégrations Disponibles</h3>

                <div class="vlp-success-box">
                    <h4>✅ Plugins supportés :</h4>
                    <ul>
                        <li><strong>GiftCode Protect v2</strong> - Gestion des codes cadeaux</li>
                        <li><strong>Bunny Stream</strong> - Diffusion vidéo optimisée</li>
                        <li><strong>Presto Player</strong> - Lecteur vidéo avancé</li>
                        <li><strong>WooCommerce</strong> - Vente de codes d'accès</li>
                    </ul>
                </div>

                <div class="vlp-info-box">
                    <p><strong>💡 Conseil :</strong> Ces pages sont des templates de base. Personnalisez-les selon vos besoins et votre identité visuelle !</p>
                </div>
    '''

    create_page_file(
        f"{pages_dir}/page-installation-configuration.php",
        "Installation & Configuration",
        installation_content,
        "Guide technique d'installation et de configuration du système"
    )

    print("\n" + "=" * 50)
    print("✅ PAGES CRÉÉES AVEC SUCCÈS!")
    print("=" * 50)
    print(f"📁 Toutes les pages ont été créées dans le dossier: {pages_dir}/")
    print("\n🚀 Prochaines étapes:")
    print("1. Copiez ces fichiers dans votre thème WordPress")
    print("2. Ou intégrez le contenu dans vos pages via l'admin WordPress")
    print("3. Personnalisez le CSS selon votre design")
    print("4. Testez les shortcodes avec des vidéos de test")
    print("\n💡 Les shortcodes utilisés:")
    print("- [vlp_video_library] → Bibliothèque complète")
    print("- [vlp_video_categories] → Navigation par catégories")  
    print("- [vlp_protected_content] → Contenu protégé par codes")
    print("- [vlp_single_video] → Vidéo individuelle")

if __name__ == "__main__":
    main()