<?php
/**
 * Page: Contenu Protégé - Exemple
 * Description: Exemple de page avec du contenu protégé par codes cadeaux
 * 
 * Generated by Video Library Protect page creator
 * Date: 2025-09-28 03:37:55
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Contenu Protégé - Exemple
 * 
 * Cette page fait partie du système Video Library Protect
 * et utilise les shortcodes et fonctionnalités du plugin.
 */

// Page Header
get_header(); ?>

<div class="vlp-page-wrapper">
    <div class="container">
        <main class="vlp-main-content">
            
            <header class="vlp-page-header">
                <h1 class="vlp-page-title">Contenu Protégé - Exemple</h1>
                <?php if (!empty("Exemple de page avec du contenu protégé par codes cadeaux")): ?>
                <p class="vlp-page-description">Exemple de page avec du contenu protégé par codes cadeaux</p>
                <?php endif; ?>
            </header>

            <div class="vlp-page-content">

                <div class="vlp-info-box">
                    <h3>🔒 Contenu Exclusif</h3>
                    <p>Cette page démontre comment protéger du contenu spécifique avec des codes cadeaux personnalisés.</p>
                </div>

                <!-- Contenu protégé par codes spécifiques -->
                [vlp_protected_content codes="VIP-ACCESS,PREMIUM-2024" message="Ce contenu exclusif nécessite un code VIP ou Premium." unlock_message="🎉 Bienvenue dans notre espace VIP !"]

                <h3>🌟 Contenu Exclusif VIP</h3>
                <p>Félicitations ! Vous avez débloqué notre contenu exclusif.</p>

                <div class="vlp-success-box">
                    <h4>🎁 Avantages VIP inclus :</h4>
                    <ul>
                        <li>✨ Accès anticipé aux nouvelles vidéos</li>
                        <li>🎥 Contenu bonus et coulisses</li>
                        <li>💬 Communauté privée VIP</li>
                        <li>📧 Newsletter exclusive avec conseils privés</li>
                        <li>🎯 Formations avancées réservées aux membres</li>
                    </ul>
                </div>

                <div class="vlp-code-example">
Codes acceptés pour cette page :
- VIP-ACCESS (accès illimité)
- PREMIUM-2024 (accès premium annuel)
                </div>

                <!-- Autre section protégée avec code différent -->
                [vlp_protected_content codes="MASTERCLASS-2024" message="Cette masterclass exclusive nécessite le code MASTERCLASS-2024"]

                <h3>🎓 Masterclass Exclusive</h3>
                <p>Cette formation approfondie vous donnera les clés pour maîtriser [votre sujet].</p>

                <video controls width="100%">
                    <source src="/path/to/exclusive-masterclass.mp4" type="video/mp4">
                    Votre navigateur ne supporte pas la lecture vidéo.
                </video>

                [/vlp_protected_content]

                [/vlp_protected_content]

                <div class="vlp-info-box">
                    <h4>🛡️ Comment fonctionne la protection :</h4>
                    <p>Le shortcode <code>[vlp_protected_content]</code> permet de protéger n'importe quel contenu avec des codes spécifiques. 
                    Seuls les utilisateurs ayant saisi un code valide peuvent voir le contenu à l'intérieur.</p>
                </div>
    
            </div>

        </main>
    </div>
</div>

<style>
.vlp-page-wrapper {
    padding: 40px 0;
    background: #f8f9fa;
    min-height: 70vh;
}

.vlp-page-header {
    text-align: center;
    margin-bottom: 40px;
    padding: 30px 0;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-page-title {
    color: #2c3e50;
    font-size: 2.5em;
    margin-bottom: 15px;
    font-weight: 600;
}

.vlp-page-description {
    color: #7f8c8d;
    font-size: 1.2em;
    max-width: 600px;
    margin: 0 auto;
    line-height: 1.6;
}

.vlp-page-content {
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-info-box {
    background: #e8f4fd;
    border-left: 4px solid #3498db;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-warning-box {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-success-box {
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-steps-list {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin: 30px 0;
}

.vlp-steps-list ol {
    counter-reset: step-counter;
    list-style: none;
    padding: 0;
}

.vlp-steps-list ol li {
    counter-increment: step-counter;
    margin: 20px 0;
    padding: 20px;
    background: white;
    border-radius: 6px;
    position: relative;
    padding-left: 60px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.vlp-steps-list ol li::before {
    content: counter(step-counter);
    position: absolute;
    left: 20px;
    top: 20px;
    background: #3498db;
    color: white;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    font-size: 14px;
}

.vlp-code-example {
    background: #2c3e50;
    color: #ecf0f1;
    padding: 20px;
    border-radius: 6px;
    font-family: 'Courier New', monospace;
    margin: 20px 0;
    overflow-x: auto;
}

.vlp-shortcode-demo {
    background: #f39c12;
    color: white;
    padding: 15px;
    border-radius: 4px;
    font-family: monospace;
    text-align: center;
    margin: 15px 0;
    font-weight: bold;
}

@media (max-width: 768px) {
    .vlp-page-title {
        font-size: 2em;
    }
    
    .vlp-page-content {
        padding: 20px;
    }
    
    .vlp-steps-list ol li {
        padding-left: 20px;
    }
    
    .vlp-steps-list ol li::before {
        position: relative;
        left: 0;
        top: 0;
        margin-right: 15px;
        margin-bottom: 10px;
    }
}
</style>

<?php get_footer(); ?>
