<?php
/**
 * Page: Installation & Configuration
 * Description: Guide technique d'installation et de configuration du système
 * 
 * Generated by Video Library Protect page creator
 * Date: 2025-09-28 03:37:55
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Installation & Configuration
 * 
 * Cette page fait partie du système Video Library Protect
 * et utilise les shortcodes et fonctionnalités du plugin.
 */

// Page Header
get_header(); ?>

<div class="vlp-page-wrapper">
    <div class="container">
        <main class="vlp-main-content">
            
            <header class="vlp-page-header">
                <h1 class="vlp-page-title">Installation & Configuration</h1>
                <?php if (!empty("Guide technique d'installation et de configuration du système")): ?>
                <p class="vlp-page-description">Guide technique d'installation et de configuration du système</p>
                <?php endif; ?>
            </header>

            <div class="vlp-page-content">

                <div class="vlp-info-box">
                    <h3>🔧 Installation et Configuration</h3>
                    <p>Guide technique pour les développeurs et administrateurs WordPress.</p>
                </div>

                <div class="vlp-steps-list">
                    <h4>⚙️ Installation du plugin :</h4>
                    <ol>
                        <li>
                            <strong>Téléchargement</strong><br>
                            Téléchargez le plugin Video Library Protect depuis votre espace client
                        </li>
                        <li>
                            <strong>Installation WordPress</strong><br>
                            Allez dans Extensions > Ajouter > Téléverser et sélectionnez le fichier ZIP
                        </li>
                        <li>
                            <strong>Activation</strong><br>
                            Activez le plugin depuis la liste des extensions
                        </li>
                        <li>
                            <strong>Configuration initiale</strong><br>
                            Le plugin créé automatiquement les tables et la page bibliothèque
                        </li>
                    </ol>
                </div>

                <h3>📁 Structure des Pages Créées</h3>

                <div class="vlp-code-example">
/video-library/                 → [vlp_video_library]
/categories-videos/             → [vlp_video_categories]
/aide-support-video/           → Documentation complète
/contenu-protege-exemple/      → Exemple de protection
</div>

                <div class="vlp-steps-list">
                    <h4>🎯 Configuration recommandée :</h4>
                    <ol>
                        <li>
                            <strong>Intégration GiftCode Protect</strong><br>
                            Installez et activez le plugin GiftCode Protect v2 pour la gestion des codes
                        </li>
                        <li>
                            <strong>Configuration Bunny Stream (optionnel)</strong><br>
                            Configurez vos clés API Bunny pour la diffusion vidéo optimisée
                        </li>
                        <li>
                            <strong>Presto Player (optionnel)</strong><br>
                            Installez Presto Player pour un lecteur vidéo avancé
                        </li>
                        <li>
                            <strong>Personnalisation CSS</strong><br>
                            Adaptez les styles dans votre thème ou via le customizer
                        </li>
                    </ol>
                </div>

                <h3>🎨 Personnalisation</h3>

                <div class="vlp-code-example">
/* CSS pour personnaliser l'apparence */
.vlp-video-library {
    /* Styles de la bibliothèque */
}

.vlp-video-card {
    /* Styles des cartes vidéo */
}

.vlp-unlock-form {
    /* Styles des formulaires de déverrouillage */
}
</div>

                <div class="vlp-warning-box">
                    <h4>⚠️ Prérequis techniques :</h4>
                    <ul>
                        <li>WordPress 5.0+</li>
                        <li>PHP 7.4+</li>
                        <li>MySQL 5.6+</li>
                        <li>Plugin GiftCode Protect v2 (recommandé)</li>
                        <li>HTTPS activé (pour la sécurité des codes)</li>
                    </ul>
                </div>

                <h3>🔌 Intégrations Disponibles</h3>

                <div class="vlp-success-box">
                    <h4>✅ Plugins supportés :</h4>
                    <ul>
                        <li><strong>GiftCode Protect v2</strong> - Gestion des codes cadeaux</li>
                        <li><strong>Bunny Stream</strong> - Diffusion vidéo optimisée</li>
                        <li><strong>Presto Player</strong> - Lecteur vidéo avancé</li>
                        <li><strong>WooCommerce</strong> - Vente de codes d'accès</li>
                    </ul>
                </div>

                <div class="vlp-info-box">
                    <p><strong>💡 Conseil :</strong> Ces pages sont des templates de base. Personnalisez-les selon vos besoins et votre identité visuelle !</p>
                </div>
    
            </div>

        </main>
    </div>
</div>

<style>
.vlp-page-wrapper {
    padding: 40px 0;
    background: #f8f9fa;
    min-height: 70vh;
}

.vlp-page-header {
    text-align: center;
    margin-bottom: 40px;
    padding: 30px 0;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-page-title {
    color: #2c3e50;
    font-size: 2.5em;
    margin-bottom: 15px;
    font-weight: 600;
}

.vlp-page-description {
    color: #7f8c8d;
    font-size: 1.2em;
    max-width: 600px;
    margin: 0 auto;
    line-height: 1.6;
}

.vlp-page-content {
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-info-box {
    background: #e8f4fd;
    border-left: 4px solid #3498db;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-warning-box {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-success-box {
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-steps-list {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin: 30px 0;
}

.vlp-steps-list ol {
    counter-reset: step-counter;
    list-style: none;
    padding: 0;
}

.vlp-steps-list ol li {
    counter-increment: step-counter;
    margin: 20px 0;
    padding: 20px;
    background: white;
    border-radius: 6px;
    position: relative;
    padding-left: 60px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.vlp-steps-list ol li::before {
    content: counter(step-counter);
    position: absolute;
    left: 20px;
    top: 20px;
    background: #3498db;
    color: white;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    font-size: 14px;
}

.vlp-code-example {
    background: #2c3e50;
    color: #ecf0f1;
    padding: 20px;
    border-radius: 6px;
    font-family: 'Courier New', monospace;
    margin: 20px 0;
    overflow-x: auto;
}

.vlp-shortcode-demo {
    background: #f39c12;
    color: white;
    padding: 15px;
    border-radius: 4px;
    font-family: monospace;
    text-align: center;
    margin: 15px 0;
    font-weight: bold;
}

@media (max-width: 768px) {
    .vlp-page-title {
        font-size: 2em;
    }
    
    .vlp-page-content {
        padding: 20px;
    }
    
    .vlp-steps-list ol li {
        padding-left: 20px;
    }
    
    .vlp-steps-list ol li::before {
        position: relative;
        left: 0;
        top: 0;
        margin-right: 15px;
        margin-bottom: 10px;
    }
}
</style>

<?php get_footer(); ?>
