<?php
/**
 * Page: Catégories de Vidéos
 * Description: Naviguez dans nos vidéos par catégories thématiques
 * 
 * Generated by Video Library Protect page creator
 * Date: 2025-09-28 03:37:55
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Catégories de Vidéos
 * 
 * Cette page fait partie du système Video Library Protect
 * et utilise les shortcodes et fonctionnalités du plugin.
 */

// Page Header
get_header(); ?>

<div class="vlp-page-wrapper">
    <div class="container">
        <main class="vlp-main-content">
            
            <header class="vlp-page-header">
                <h1 class="vlp-page-title">Catégories de Vidéos</h1>
                <?php if (!empty("Naviguez dans nos vidéos par catégories thématiques")): ?>
                <p class="vlp-page-description">Naviguez dans nos vidéos par catégories thématiques</p>
                <?php endif; ?>
            </header>

            <div class="vlp-page-content">

                <!-- Shortcode pour afficher les catégories -->
                <div class="vlp-info-box">
                    <h3>📁 Explorez nos Catégories</h3>
                    <p>Découvrez nos vidéos organisées par thèmes et sujets. Chaque catégorie peut avoir son propre niveau de protection.</p>
                </div>

                <!-- Shortcode des catégories vidéo -->
                [vlp_video_categories layout="grid" columns="3" show_count="true" show_protected="true"]

                <div class="vlp-steps-list">
                    <h4>🚀 Comment naviguer dans les catégories :</h4>
                    <ol>
                        <li>
                            <strong>Parcourez les catégories</strong><br>
                            Chaque catégorie affiche le nombre de vidéos et son statut de protection
                        </li>
                        <li>
                            <strong>Identifiez les protections</strong><br>
                            L'icône 🔒 indique qu'un code cadeau est requis pour accéder au contenu
                        </li>
                        <li>
                            <strong>Cliquez pour explorer</strong><br>
                            Accédez directement aux vidéos de la catégorie qui vous intéresse
                        </li>
                        <li>
                            <strong>Utilisez vos codes</strong><br>
                            Saisissez votre code cadeau pour débloquer une catégorie entière
                        </li>
                    </ol>
                </div>

                <div class="vlp-warning-box">
                    <h4>🔑 Codes Cadeaux Requis</h4>
                    <p>Certaines catégories nécessitent un code cadeau valide. Une fois un code saisi, vous aurez accès à toutes les vidéos de cette catégorie !</p>
                </div>
    
            </div>

        </main>
    </div>
</div>

<style>
.vlp-page-wrapper {
    padding: 40px 0;
    background: #f8f9fa;
    min-height: 70vh;
}

.vlp-page-header {
    text-align: center;
    margin-bottom: 40px;
    padding: 30px 0;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-page-title {
    color: #2c3e50;
    font-size: 2.5em;
    margin-bottom: 15px;
    font-weight: 600;
}

.vlp-page-description {
    color: #7f8c8d;
    font-size: 1.2em;
    max-width: 600px;
    margin: 0 auto;
    line-height: 1.6;
}

.vlp-page-content {
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-info-box {
    background: #e8f4fd;
    border-left: 4px solid #3498db;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-warning-box {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-success-box {
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-steps-list {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin: 30px 0;
}

.vlp-steps-list ol {
    counter-reset: step-counter;
    list-style: none;
    padding: 0;
}

.vlp-steps-list ol li {
    counter-increment: step-counter;
    margin: 20px 0;
    padding: 20px;
    background: white;
    border-radius: 6px;
    position: relative;
    padding-left: 60px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.vlp-steps-list ol li::before {
    content: counter(step-counter);
    position: absolute;
    left: 20px;
    top: 20px;
    background: #3498db;
    color: white;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    font-size: 14px;
}

.vlp-code-example {
    background: #2c3e50;
    color: #ecf0f1;
    padding: 20px;
    border-radius: 6px;
    font-family: 'Courier New', monospace;
    margin: 20px 0;
    overflow-x: auto;
}

.vlp-shortcode-demo {
    background: #f39c12;
    color: white;
    padding: 15px;
    border-radius: 4px;
    font-family: monospace;
    text-align: center;
    margin: 15px 0;
    font-weight: bold;
}

@media (max-width: 768px) {
    .vlp-page-title {
        font-size: 2em;
    }
    
    .vlp-page-content {
        padding: 20px;
    }
    
    .vlp-steps-list ol li {
        padding-left: 20px;
    }
    
    .vlp-steps-list ol li::before {
        position: relative;
        left: 0;
        top: 0;
        margin-right: 15px;
        margin-bottom: 10px;
    }
}
</style>

<?php get_footer(); ?>
