<?php
/**
 * Page: Aide & Support Vidéo
 * Description: Guide complet pour utiliser la bibliothèque vidéo et les codes cadeaux
 * 
 * Generated by Video Library Protect page creator
 * Date: 2025-09-28 03:37:55
 */

// Prevent direct access
if (!defined('ABSPATH')) {
    exit;
}

/**
 * Aide & Support Vidéo
 * 
 * Cette page fait partie du système Video Library Protect
 * et utilise les shortcodes et fonctionnalités du plugin.
 */

// Page Header
get_header(); ?>

<div class="vlp-page-wrapper">
    <div class="container">
        <main class="vlp-main-content">
            
            <header class="vlp-page-header">
                <h1 class="vlp-page-title">Aide & Support Vidéo</h1>
                <?php if (!empty("Guide complet pour utiliser la bibliothèque vidéo et les codes cadeaux")): ?>
                <p class="vlp-page-description">Guide complet pour utiliser la bibliothèque vidéo et les codes cadeaux</p>
                <?php endif; ?>
            </header>

            <div class="vlp-page-content">

                <div class="vlp-info-box">
                    <h3>❓ Centre d'Aide - Video Library Protect</h3>
                    <p>Trouvez rapidement les réponses à vos questions sur l'utilisation de notre bibliothèque vidéo et des codes cadeaux.</p>
                </div>

                <div class="vlp-steps-list">
                    <h4>🚀 Guide de démarrage rapide :</h4>
                    <ol>
                        <li>
                            <strong>Découvrez la bibliothèque</strong><br>
                            Rendez-vous sur la <a href="/video-library/">page de la bibliothèque vidéo</a> pour voir toutes les vidéos disponibles
                        </li>
                        <li>
                            <strong>Explorez les catégories</strong><br>
                            Naviguez par thème sur la <a href="/categories-videos/">page des catégories</a>
                        </li>
                        <li>
                            <strong>Regardez les aperçus gratuits</strong><br>
                            Toutes les vidéos ont un aperçu gratuit pour vous aider à choisir
                        </li>
                        <li>
                            <strong>Utilisez vos codes cadeaux</strong><br>
                            Saisissez votre code pour débloquer la vidéo complète ou une catégorie entière
                        </li>
                    </ol>
                </div>

                <h3>🔑 Utilisation des Codes Cadeaux</h3>

                <div class="vlp-warning-box">
                    <h4>Format des codes :</h4>
                    <ul>
                        <li>Entre 3 et 50 caractères</li>
                        <li>Lettres, chiffres et tirets autorisés</li>
                        <li>Pas de distinction majuscules/minuscules</li>
                        <li>Exemples : <code>NOEL2024</code>, <code>promo-hiver</code>, <code>VIP-ACCESS</code></li>
                    </ul>
                </div>

                <div class="vlp-steps-list">
                    <h4>📝 Comment saisir un code cadeau :</h4>
                    <ol>
                        <li>
                            <strong>Sur une vidéo protégée</strong><br>
                            Cliquez sur la vidéo, puis saisissez votre code dans le formulaire qui apparaît
                        </li>
                        <li>
                            <strong>Pour une catégorie entière</strong><br>
                            Le code vous donnera accès à toutes les vidéos de cette catégorie
                        </li>
                        <li>
                            <strong>Sur du contenu spécifique</strong><br>
                            Certaines pages ont du contenu protégé par des codes particuliers
                        </li>
                        <li>
                            <strong>Accès site entier</strong><br>
                            Certains codes premium donnent accès à l'ensemble du site
                        </li>
                    </ol>
                </div>

                <h3>🎥 Types de Protection</h3>

                <div class="vlp-info-box">
                    <h4>🆓 Vidéos gratuites</h4>
                    <p>Accès immédiat et complet à la vidéo, sans code requis.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>🔒 Vidéos protégées individuellement</h4>
                    <p>Chaque vidéo a ses propres codes d'accès. L'aperçu est gratuit, la vidéo complète nécessite un code.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>📁 Catégories protégées</h4>
                    <p>Un seul code donne accès à toutes les vidéos de la catégorie.</p>
                </div>

                <div class="vlp-warning-box">
                    <h4>🌐 Protection site entier</h4>
                    <p>Certains codes premium donnent accès à l'intégralité du contenu du site.</p>
                </div>

                <h3>🛠️ Résolution de problèmes</h3>

                <div class="vlp-steps-list">
                    <h4>❌ Problèmes courants et solutions :</h4>
                    <ol>
                        <li>
                            <strong>"Code invalide"</strong><br>
                            ✅ Vérifiez l'orthographe et les espaces<br>
                            ✅ Assurez-vous que le code n'est pas expiré<br>
                            ✅ Contactez-nous si le problème persiste
                        </li>
                        <li>
                            <strong>"La vidéo ne se charge pas"</strong><br>
                            ✅ Vérifiez votre connexion internet<br>
                            ✅ Essayez de rafraîchir la page<br>
                            ✅ Désactivez temporairement les bloqueurs de publicité
                        </li>
                        <li>
                            <strong>"J'ai perdu mon code"</strong><br>
                            ✅ Vérifiez vos emails de confirmation<br>
                            ✅ Consultez votre compte utilisateur<br>
                            ✅ Contactez notre support client
                        </li>
                        <li>
                            <strong>"Le code ne fonctionne pas sur cette vidéo"</strong><br>
                            ✅ Vérifiez que le code correspond bien à cette vidéo<br>
                            ✅ Certains codes sont spécifiques à des catégories<br>
                            ✅ Les codes site-wide fonctionnent partout
                        </li>
                    </ol>
                </div>

                <h3>🎯 Shortcodes Disponibles</h3>

                <div class="vlp-code-example">
                    <h4>Pour les développeurs et administrateurs :</h4>

                    <!-- Bibliothèque complète -->
                    [vlp_video_library]
                    
                    <!-- Bibliothèque avec options -->
                    [vlp_video_library category="formation" limit="8" columns="4" layout="grid"]
                    
                    <!-- Catégories uniquement -->
                    [vlp_video_categories layout="grid" show_count="true"]
                    
                    <!-- Vidéo spécifique -->
                    [vlp_single_video id="123" autoplay="false" show_info="true"]
                    [vlp_single_video slug="ma-video" width="100%" show_related="true"]
                    
                    <!-- Contenu protégé -->
                    [vlp_protected_content codes="CODE1,CODE2"]Contenu secret[/vlp_protected_content]
                </div>

                <h3>📞 Besoin d'aide supplémentaire ?</h3>

                <div class="vlp-success-box">
                    <h4>💬 Contactez-nous :</h4>
                    <ul>
                        <li>📧 <strong>Email :</strong> support@votresite.com</li>
                        <li>💬 <strong>Chat en direct :</strong> Disponible 9h-18h</li>
                        <li>📱 <strong>Téléphone :</strong> +33 1 23 45 67 89</li>
                        <li>🎫 <strong>Système de tickets :</strong> <a href="/support/">Créer un ticket</a></li>
                    </ul>
                    <p><strong>⏰ Temps de réponse moyen :</strong> Moins de 2 heures en semaine</p>
                </div>

                <div class="vlp-info-box">
                    <h4>📚 Ressources utiles :</h4>
                    <ul>
                        <li><a href="/video-library/">🎥 Bibliothèque Vidéo</a></li>
                        <li><a href="/categories-videos/">📁 Catégories de Vidéos</a></li>
                        <li><a href="/mon-compte/">👤 Mon Compte</a></li>
                        <li><a href="/faq/">❓ FAQ Complète</a></li>
                    </ul>
                </div>
    
            </div>

        </main>
    </div>
</div>

<style>
.vlp-page-wrapper {
    padding: 40px 0;
    background: #f8f9fa;
    min-height: 70vh;
}

.vlp-page-header {
    text-align: center;
    margin-bottom: 40px;
    padding: 30px 0;
    background: white;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-page-title {
    color: #2c3e50;
    font-size: 2.5em;
    margin-bottom: 15px;
    font-weight: 600;
}

.vlp-page-description {
    color: #7f8c8d;
    font-size: 1.2em;
    max-width: 600px;
    margin: 0 auto;
    line-height: 1.6;
}

.vlp-page-content {
    background: white;
    padding: 40px;
    border-radius: 8px;
    box-shadow: 0 2px 10px rgba(0,0,0,0.1);
}

.vlp-info-box {
    background: #e8f4fd;
    border-left: 4px solid #3498db;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-warning-box {
    background: #fff3cd;
    border-left: 4px solid #ffc107;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-success-box {
    background: #d4edda;
    border-left: 4px solid #28a745;
    padding: 20px;
    margin: 20px 0;
    border-radius: 4px;
}

.vlp-steps-list {
    background: #f8f9fa;
    padding: 30px;
    border-radius: 8px;
    margin: 30px 0;
}

.vlp-steps-list ol {
    counter-reset: step-counter;
    list-style: none;
    padding: 0;
}

.vlp-steps-list ol li {
    counter-increment: step-counter;
    margin: 20px 0;
    padding: 20px;
    background: white;
    border-radius: 6px;
    position: relative;
    padding-left: 60px;
    box-shadow: 0 2px 5px rgba(0,0,0,0.1);
}

.vlp-steps-list ol li::before {
    content: counter(step-counter);
    position: absolute;
    left: 20px;
    top: 20px;
    background: #3498db;
    color: white;
    width: 30px;
    height: 30px;
    border-radius: 50%;
    display: flex;
    align-items: center;
    justify-content: center;
    font-weight: bold;
    font-size: 14px;
}

.vlp-code-example {
    background: #2c3e50;
    color: #ecf0f1;
    padding: 20px;
    border-radius: 6px;
    font-family: 'Courier New', monospace;
    margin: 20px 0;
    overflow-x: auto;
}

.vlp-shortcode-demo {
    background: #f39c12;
    color: white;
    padding: 15px;
    border-radius: 4px;
    font-family: monospace;
    text-align: center;
    margin: 15px 0;
    font-weight: bold;
}

@media (max-width: 768px) {
    .vlp-page-title {
        font-size: 2em;
    }
    
    .vlp-page-content {
        padding: 20px;
    }
    
    .vlp-steps-list ol li {
        padding-left: 20px;
    }
    
    .vlp-steps-list ol li::before {
        position: relative;
        left: 0;
        top: 0;
        margin-right: 15px;
        margin-bottom: 10px;
    }
}
</style>

<?php get_footer(); ?>
